name: ReQue
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pandas=0.23.3
  - numpy>=1.18.1
  - requests=2.22.0
  - urllib3=1.25.8
  - networkx=2.2
  - nltk=3.4
  - pip=19.0.3
  - pip:
    - gensim==3.8.1
    - scipy==1.4.*
    - pywsd==1.2.4
    - wn==0.0.23
    - tagme==0.1.3
    - community==1.0.0b1
    - bs4==0.0.1
    - lxml
    - python-louvain==0.13
    - coloredlogs==14.0
    - pydantic==1.5
    - scikit-learn>=0.22
    - spacy==2.2.4
    - tensorboard>=2.1.0
    - tensorflow>=2.2.0rc1
    - tokenizers==0.9.4
    - tqdm==4.45.0
    - transformers==4.0.0
    - sentencepiece==0.1.94
    - torch==1.7.1
    - pyserini==0.10.0.1
    
